services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # เชื่อมโยงโฟลเดอร์หลักของคุณเข้ากับ Container ในชื่อ /images
      - E:\S25_DRR\xeno:/images
    environment:
      - DATABASE_URL=sqlite:///./pavement.db
